/** Ordered from most to least common; the seeder weights picks by position. */
export const NATIONALITIES = [
  'American',
  'British',
  'Indian',
  'German',
  'French',
  'Canadian',
  'Australian',
  'Brazilian',
  'Spanish',
  'Italian',
  'Mexican',
  'Japanese',
  'Chinese',
  'Emirati',
  'Egyptian',
  'Nigerian',
  'South African',
  'Dutch',
  'Swedish',
  'Norwegian',
  'Irish',
  'Portuguese',
  'Argentinian',
  'Turkish',
  'Korean',
  'Filipino',
  'Pakistani',
  'Saudi',
  'Polish',
  'New Zealander',
] as const;

export const HOBBIES = [
  'Reading',
  'Traveling',
  'Cooking',
  'Photography',
  'Hiking',
  'Gaming',
  'Music',
  'Running',
  'Cycling',
  'Yoga',
  'Swimming',
  'Painting',
  'Gardening',
  'Chess',
  'Dancing',
  'Writing',
  'Fishing',
  'Camping',
  'Football',
  'Basketball',
  'Tennis',
  'Knitting',
  'Baking',
  'Skiing',
  'Surfing',
  'Climbing',
  'Movies',
  'Podcasts',
  'Volunteering',
  'Meditation',
  'Board Games',
  'Pottery',
  'Birdwatching',
  'Calligraphy',
  'Astronomy',
  'Woodworking',
  'Skateboarding',
  'Origami',
  'Karaoke',
  'Archery',
] as const;
